package main

import (
	"net/http"
	"text/template"
)

/* Global Constants */
const (
	TemplateData404 = `<!DOCTYPE html>
<html>
	<head>
		<title>Page Not Found - {{.}}</title>
	</head>
	<body>
		<h2>404 Not Found</h2>
		<h3>Requested resource {{.}} was not found</h3>
		<hr>
		<i>Generated by Dead Simple Proxy</i>
	<body>
</html>`

	TemplateDataStats = `<!DOCTYPE html>
<html>
	<head>
		<title>Proxy Statistics</title>
		<style>
			.heading {
				text-decoration: underline;
			};
			table {
				border-collapse: collapse;
				width: 100%;
			}
			th, td {
				text-align: left;
				padding: 0 20px 0 20px;
			}
			tr:nth-child(even) {
				background-color: #f2f2f2;
			}
			thead {
				font-weight: bold;
				background-color: #ccc;
			}
		</style>
	</head>
	<body>
		<h2 class=heading>Dead Simple Proxy, Statistics Page</h2>
		<h3>Global Statistics</h3>
		<table>
			<thead>
				<tr>
					<td>Parameter</td>
					<td>Value</td>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>Active Requests</td>
					<td>{{.ActiveRequests}}</td>
				</tr>
				<tr>
					<td>Requests per Second</td>
					<td>{{.RequestsPerSecond}}</td>
				</tr>
				<tr>
					<td>Total Requests</td>
					<td>{{.TotalRequests}}</td>
				</tr>
				<tr>
					<td>Server Uptime</td>
					<td>{{.ServerUptime}}</td>
				</tr>
			</tbody>
		</table>
		<h3>Configured Endpoints</h3>
		<table>
			<thead>
				<tr>
					<td>&#35;</td>
					<td>Local Path</td>
					<td>Upstream Address</td>
					<td>Options</td>
				</tr>
			</thead>
			<tbody>
			{{range $i, $EndPoint := .Backend}}
				<tr>
					<td>{{$i}}</td>
					<td>{{$EndPoint.LocalPath}}</td>
					<td>{{$EndPoint.Upstream}}</td>
					<td>-</td>
				</tr>
			{{end}}
			</tbody>
		</table>
	</body>
</html>
`
)

/* Global Variables */
var (
	Template404   *template.Template
	TemplateStats *template.Template
)

/* Initialize global templates */
func init() {
	Template404 = template.Must(
		template.New("404").Parse(TemplateData404),
	)
	TemplateStats = template.Must(
		template.New("stats").Parse(TemplateDataStats),
	)
}

/* Render404 generates a 404 Not Found page */
func Render404(w http.ResponseWriter, what string) error {
	w.WriteHeader(http.StatusNotFound)
	if err := Template404.Execute(w, what); err != nil {
		return err
	}
	return nil
}

/* RenderStats generates a statistics page */
func RenderStats(w http.ResponseWriter, data interface{}) error {
	return TemplateStats.Execute(w, data)
}
